cookitnow_web/blueprints/recipe/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, make_response, session
import requests
from app import app
from models.upload_recipe import UploadRecipe
from models.user import User
from models.favourite import Favourite
import json
import os
from werkzeug import secure_filename
from flask_login import login_required, current_user, login_user, logout_user


UPLOAD_FOLDER = 'cookitnow_web/static/images/uploaded_img/'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


recipe_blueprint = Blueprint('recipe',
                            __name__,
                            template_folder='templates')


@recipe_blueprint.route('/', methods=['GET', 'POST'])
def recipe():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/recipes/findByIngredients?ingredients=" +
            (request.form['ingredient_name']) +
            "&number=30&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/recipe_search.html", response=json_response) if json_response != [] else render_template(
            "recipe/recipe_search.html", response="")
    else:
        return render_template("recipe/recipe_search.html") 


@recipe_blueprint.route('/<recipe_id>', methods=['GET'])
def recipe_details(recipe_id):
    response = requests.get("https://api.spoonacular.com/recipes/"+recipe_id+"/information?includeNutrition=true&apiKey="+app.config.get("SPOON_API"))
    similar_recipe = requests.get("https://api.spoonacular.com/recipes/"+recipe_id+"/similar?number=7&apiKey="+app.config.get("SPOON_API"))
    return make_response(render_template("recipe/recipe_details.html", recipe_id=json.loads(response.text), recipe_similar =json.loads(similar_recipe.text)), 200)


@recipe_blueprint.route('/random_recipe', methods=['GET'])
def random_recipe():
    random_content = requests.get("https://api.spoonacular.com/recipes/random?number=30&apiKey="+app.config.get("SPOON_API"))
    json_response = json.loads(random_content.text)
    return make_response(render_template("recipe/random_recipe.html", response=json_response), 200)


@recipe_blueprint.route('/cooking_video', methods=['GET', 'POST'])
def cooking_video():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/food/videos/search?includeIngredients=" +
            (request.form['ingredient_name_video']) +
            "&number=20&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/cooking_video.html", response=json_response) if json_response != [] else render_template(
            "recipe/cooking_video.html", response="")
    else:
        return render_template("recipe/cooking_video.html") 


@recipe_blueprint.route('/show_customize_recipe', methods=['GET'])
def show_customize_recipe():
    all_recipe = UploadRecipe.select()
    return render_template("recipe/show_customize_recipe.html", all_recipe = all_recipe) 


@recipe_blueprint.route('/upload_recipe', methods=['GET'])
def upload_recipe():
    return render_template("recipe/upload_recipe.html") 


@recipe_blueprint.route('/upload', methods=['POST'])
def create_recipe():
    data = request.form

    if "recipeimage" not in request.files:
        flash("Please select an image for the recipe!")
        return redirect(url_for("recipe.upload_recipe"))
    file = request.files['recipeimage']
    if file.filename == "":
        flash("Please select an image for the recipe!")
        return redirect(url_for("recipe.upload_recipe"))
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'],filename))
    else:
        flash("Could not upload image, please go back and try again")
        return redirect(url_for("recipe.upload_recipe"))
        
    url = file.filename
    create_new_recipe = UploadRecipe(
        r_title = data.get('recipetitle'), 
        r_cookingtime = data.get('recipetime'),
        r_image_url = url,
        r_serving = data.get('recipeserve'), 
        r_ingredient = data.get('recipeingredient'), 
        r_step = data.get('recipestep'), 
        r_about = data.get('recipeabout')
    )

    if create_new_recipe.save():   
        return redirect(url_for("recipe.show_customize_recipe"))
    else:
        return redirect(url_for("recipe.upload_recipe"))



@recipe_blueprint.route('/customize/<id>', methods=["GET"])
def show_recipe(id):
    c_recipe = UploadRecipe.get_or_none(UploadRecipe.id == id)
    return render_template("recipe/show_recipe.html", c_recipe = c_recipe)    



@recipe_blueprint.route('/customize/<id>/edit', methods=["GET"])
def edit_recipe(id):
    edit_recipe = UploadRecipe.get_or_none(UploadRecipe.id == id)
    return render_template("recipe/edit_recipe.html", edit_recipe = edit_recipe, id = id) 



@recipe_blueprint.route('/<id>/edit', methods=["POST"])
def update_recipe(id):
    update_recipe = UploadRecipe.get_or_none(UploadRecipe.id == id)
    data = request.form

    if update_recipe:
        if "recipeimage" not in request.files:
            flash("Please select an image for the recipe!")
            return redirect(url_for("recipe.edit_recipe",id = id))
        file = request.files['recipeimage']
        if file.filename == "":
            flash("Please select an image for the recipe!")
            return redirect(url_for("recipe.edit_recipe",id = id))
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'],filename))
        else:
            flash("Could not upload image, please go back and try again")
            return redirect(url_for("recipe.edit_recipe",id = id))
            
        url = file.filename

        update_recipe.r_title = data.get('recipetitle')
        update_recipe.r_cookingtime = data.get('recipetime')
        update_recipe.r_image_url = url
        update_recipe.r_serving = data.get('recipeserve')
        update_recipe.r_ingredient = data.get('recipeingredient')
        update_recipe.r_step = data.get('recipestep')
        update_recipe.r_about = data.get('recipeabout')
        
        

        if update_recipe.save():   
            return redirect(url_for("recipe.show_recipe", id=id))
        else:
            return redirect(url_for("recipe.edit_recipe", id=id))
    
    return render_template("recipe/edit_recipe.html", update_recipe = update_recipe, id = id)          


@recipe_blueprint.route('/meal_plan', methods=["GET"])
def meal_plan():
    return render_template("recipe/meal_plan.html")

@recipe_blueprint.route('/search_meal_plan', methods=['GET', 'POST'])
def search_meal_plan():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/mealplanner/generate?timeFrame=day&targetCalories=" + 
            (request.form['caloriesperday']) + "&diet=" +
            (request.form['diettype']) + "&exclude=" +
            (request.form['exclude_ingredient']) +
            "&number=20&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/meal_plan_result.html", response=json_response) if json_response != [] else render_template(
            "recipe/meal_plan_result.html", response="")
    else:
        return render_template("recipe/meal_plan.html") 


@recipe_blueprint.route('/search_meal_plan_weekly', methods=['GET', 'POST'])
def search_meal_plan_weekly():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/mealplanner/generate?timeFrame=week&targetCalories=" + 
            (request.form['caloriesperday']) + "&diet=" +
            (request.form['diettype']) + "&exclude=" +
            (request.form['exclude_ingredient']) +
            "&number=20&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/meal_plan_weekly_result.html", response=json_response) if json_response != [] else render_template(
            "recipe/meal_plan_weekly_result.html", response="")
    else:
        return render_template("recipe/meal_plan.html")         

cookitnow_web/blueprints/users/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, session
from models.user import User
from werkzeug.security import check_password_hash
import re
from flask_login import login_required, current_user, login_user, logout_user


users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route("/", methods=['POST'])
def create():
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    create_new_user = User(username = username, email = email, password = password)

    duplicate_username = User.get_or_none(User.username == username)
    duplicate_email = User.get_or_none(User.email == email)

    if create_new_user.save():
        flash("Sign up successfully", 'success')
        return redirect(url_for("users.login"))
    else:
        if duplicate_username: 
            flash("- This username has been used, please try another username")

        if duplicate_email:
            flash("- This email has been used, please try another email") 

        if len(password) < 6:
            flash("- Password must be at least 6 characters")

        if not re.search("[a-z]", password):
            flash("- Password must include lowercase and uppercase")
            
        if not re.search("[A-Z]", password):
            flash("- Password must include lowercase and uppercase")

        return redirect(url_for("users.new"))


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    user = User.get_or_none(User.username == username)
    return render_template("users/userprofile.html", user = user)


@users_blueprint.route('/login', methods=["GET"])
def login():
    return render_template("users/login.html")


@users_blueprint.route('/login/session', methods=[ 'POST' ])
def login_session():

    data = request.form
    user = User.get_or_none(username= data.get('username'))

    if user:
        hashed_password = user.password_hash # password hash stored in database for a specific user
        result = check_password_hash(hashed_password, data.get('password')) # what is result? Test it in Flask shell and implement it in your view function!

        if result:
           # session["user_id"] = user.id
            login_user(user)
            flash("Login successfully", 'success')
            return redirect(url_for('users.show',username = user.username))
        else:
            flash("Wrong password", 'error')
            return redirect(url_for('users.login'))
    else:
        flash("User not found", 'error')
        return redirect(url_for('users.login'))


@users_blueprint.route('/logout', methods=['POST'])
def logout():
    logout_user()
    flash('Signout Successfully', 'success')
    return redirect(url_for('users.login'))

    data = request.form
    user = User.get_or_none(username= data.get('username'))

    if user:
        hashed_password = user.password_hash # password hash stored in database for a specific user
        result = check_password_hash(hashed_password, data.get('password')) # what is result? Test it in Flask shell and implement it in your view function!

        if result:
           # session["user_id"] = user.id
            login_user(user)
            flash("Login successfully", 'success')
            return redirect(url_for('users.show',username = user.username))
        else:
            flash("Wrong password", 'error')
            return redirect(url_for('users.login'))
    else:
        flash("User not found", 'error')
        return redirect(url_for('users.login'))

cookitnow_web/templates/_layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.ico') }}">

    {% assets "home_css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% assets "home_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />

    {% block header %}
    {% endblock %}

    <title>
      {% block title %}
      {% endblock %} CookItNow
    </title>

  </head>
  <body>
    {% include "navigation.html" %}

    
    {% block content %}
    {% endblock %}
    


<script>

$(document).ready(function () {
  $(".nav-list ul li a.dashboard").click(function (e) {
      e.preventDefault();
      $(".dashboard-dd").fadeToggle();
  });

  $(".mobile-hamburger").click(function (e) {
      e.preventDefault();
      $(".nav-bar .nav-list").toggleClass("slide");
  });

  $(function() {
    setTimeout(function() {
      $(".flashes").fadeOut()
    }, 3000);
  });	

  $(".close-flashes").click(function (e) {
      e.preventDefault();
      $(".flashes").fadeOut();
  });

});
	


$(document).mouseup(function(e) 
{
  var button =$(".nav-list ul li a.dashboard");
    var container = $(".dashboard-dd");

    // if the target of the click isn't the container nor a descendant of the container
    if (!container.is(e.target) && container.has(e.target).length === 0 && !button.is(e.target)) 
    {
        container.fadeOut(200);
    }

});
</script>

    <script type="text/javascript" language="javascript" src="/static/js/recipe_details.js"></script>
  </body>
</html>

cookitnow_web/templates/home.html
{% extends "_layout.html" %}
{% block content %}
<div class="homepage">
  <div>
    <h1>Finding Some New Recipe To Cook?</h1>
    <h2>Lets see what you have in your house</h2>

    <div class="search-recipe">
      <form method="POST" autocomplete="off" action="{{url_for('recipe.recipe')}}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class='input-group'>
            <input id="autocomplete" class='input-field' type='text' name='ingredient_name' placeholder='Search Ingredient : Apple, Onion, Butter, etc.....'/>
            <span class="input-group-btn">
              <button id="searchBtn" type='submit' class='btn btn-default'>
                <i class="fas fa-search"></i>
              </button>
            </span>
        </div>
      </form>
    </div>
    <br><br>
    <h2>OR</h2>
    <h1>Learn From Amateur and Professional</h1>
    <h2>Check out some amazing cooking video here and learn from them! </h2>
    <div class="search-recipe">
      <form method="POST" autocomplete="off" action="{{url_for('recipe.cooking_video')}}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class='input-group'>
            <input id="autocomplete" class='input-field' type='text' name='ingredient_name_video' placeholder='Search Ingredient : Chicken, Pasta, Rice'/>
            <span class="input-group-btn">
              <button id="searchBtn" type='submit' class='btn btn-default'>
                <i class="fas fa-search"></i>
              </button>
            </span>
        </div>
      </form>
    </div>

    
  </div>  
</div>
{% endblock %}

cookitnow_web/templates/navigation.html
<!-- if this is home page load this -->
{% if request.endpoint == 'home'  %}
<div class="nav-bar nav-home">
    <div class="logo"><a href="/"><img src="/static/images/cookitnow-logo-white.png"></a></div>
    <div class="nav-list">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="{{url_for('recipe.meal_plan')}}">Meal Planning</a></li>
            <li><a href="{{url_for('recipe.random_recipe')}}">Random Recipe</a></li>
            <li><a href="{{url_for('recipe.show_customize_recipe')}}">Our Original Recipe</a></li>
            {% if current_user.get_id() == 1 %}
            <li><a href="{{url_for('recipe.upload_recipe')}}">Upload Recipe</a></li>
            {% endif %}

            {% if current_user.is_authenticated %}
            <li>
                <a class="dashboard">{{current_user.username}}</a>
                <div class="dashboard-dd">
                    <a href="{{url_for('users.show', username = current_user.username)}}">Dashboard</a>
                    <form action="{{url_for('users.logout')}}" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type='submit' value="Logout" class="logout">
                    </form> 
                </div>
            </li>
            {% else %}
            <li><a href="{{url_for('users.login')}}">Login</a></li>
            <li><a href="{{url_for('users.new')}}" class="signup">SignUp</a></li>
            {% endif %}
        </ul> 
    </div>

    <div class="mobile-hamburger">
        <i class="fas fa-bars"></i>
    </div>
</div>

{% else %}
<!-- not home page load this -->
<div class="nav-bar">
    <div class="logo"><a href="/"><img src="/static/images/cookitnow-logo.png"></a></div>
    <div class="nav-list">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="{{url_for('recipe.meal_plan')}}">Meal Planning</a></li>
            <li><a href="{{url_for('recipe.random_recipe')}}">Random Recipe</a></li>
            <li><a href="{{url_for('recipe.show_customize_recipe')}}">Our Original Recipe</a></li>
            {% if current_user.get_id() == 1 %}
            <li><a href="{{url_for('recipe.upload_recipe')}}">Upload Recipe</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li>
                <a class="dashboard">{{current_user.username}}</a>
                <div class="dashboard-dd">
                    <a href="{{url_for('users.show', username = current_user.username)}}">Dashboard</a>
                    <form action="{{url_for('users.logout')}}" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type='submit' value="Logout" class="logout">
                    </form> 
                </div>
            </li>
            {% else %}
            <li><a href="{{url_for('users.login')}}">Login</a></li>
            <li><a href="{{url_for('users.new')}}" class="signup">SignUp</a></li>
            {% endif %}
        </ul>
    </div>

    <div class="mobile-hamburger">
        <i class="fas fa-bars"></i>
    </div>
</div>

{% endif %}

cookitnow_web/templates/search_header.html
<div class="allpage-search">
    <div class="search-recipe">
        <form method="POST" autocomplete="off" action="{{url_for('recipe.recipe')}}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class='input-group'>
            <input id="autocomplete" class='input-field' type='text' name='ingredient_name' placeholder='Search Ingredient : Apple, Onion, Butter, etc.....'/>
            <span class="input-group-btn">
            <button id="searchBtn" type='submit' class='btn btn-default'>
                <i class="fas fa-search"></i>
            </button>
            </span>
        </div>
        </form>
    </div>
</div>

cookitnow_web/templates/search_header_video.html
<div class="allpage-search">
    <div class="search-recipe">
        <form method="POST" autocomplete="off" action="{{url_for('recipe.cooking_video')}}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class='input-group'>
            <input id="autocomplete" class='input-field' type='text' name='ingredient_name_video' placeholder='Search Ingredient : Chicken, Pasta, Rice'/>
            <span class="input-group-btn">
            <button id="searchBtn" type='submit' class='btn btn-default'> 
                <i class="fas fa-search"></i>
            </button>
            </span>
        </div>
        </form>
    </div>
</div>