cookitnow_web/blueprints/recipe/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, make_response, session
import requests
from app import app
from models.upload_recipe import UploadRecipe
from models.user import User
from models.favourite import Favourite
import json
import os
from werkzeug import secure_filename
from flask_login import login_required, current_user, login_user, logout_user


UPLOAD_FOLDER = 'cookitnow_web/static/images/uploaded_img/'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


recipe_blueprint = Blueprint('recipe',
                            __name__,
                            template_folder='templates')


@recipe_blueprint.route('/', methods=['GET', 'POST'])
def recipe():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/recipes/findByIngredients?ingredients=" +
            (request.form['ingredient_name']) +
            "&number=30&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/recipe_search.html", response=json_response) if json_response != [] else render_template(
            "recipe/recipe_search.html", response="")
    else:
        return render_template("recipe/recipe_search.html") 


@recipe_blueprint.route('/<recipe_id>', methods=['GET'])
def recipe_details(recipe_id):
    response = requests.get("https://api.spoonacular.com/recipes/"+recipe_id+"/information?includeNutrition=true&apiKey="+app.config.get("SPOON_API"))
    similar_recipe = requests.get("https://api.spoonacular.com/recipes/"+recipe_id+"/similar?number=7&apiKey="+app.config.get("SPOON_API"))
    return make_response(render_template("recipe/recipe_details.html", recipe_id=json.loads(response.text), recipe_similar =json.loads(similar_recipe.text)), 200)


@recipe_blueprint.route('/random_recipe', methods=['GET'])
def random_recipe():
    random_content = requests.get("https://api.spoonacular.com/recipes/random?number=30&apiKey="+app.config.get("SPOON_API"))
    json_response = json.loads(random_content.text)
    return make_response(render_template("recipe/random_recipe.html", response=json_response), 200)


@recipe_blueprint.route('/cooking_video', methods=['GET', 'POST'])
def cooking_video():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/food/videos/search?includeIngredients=" +
            (request.form['ingredient_name_video']) +
            "&number=20&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/cooking_video.html", response=json_response) if json_response != [] else render_template(
            "recipe/cooking_video.html", response="")
    else:
        return render_template("recipe/cooking_video.html") 


@recipe_blueprint.route('/show_customize_recipe', methods=['GET'])
def show_customize_recipe():
    all_recipe = UploadRecipe.select()
    return render_template("recipe/show_customize_recipe.html", all_recipe = all_recipe) 


@recipe_blueprint.route('/upload_recipe', methods=['GET'])
def upload_recipe():
    return render_template("recipe/upload_recipe.html") 


@recipe_blueprint.route('/upload', methods=['POST'])
def create_recipe():
    data = request.form

    if "recipeimage" not in request.files:
        flash("Please select an image for the recipe!")
        return redirect(url_for("recipe.upload_recipe"))
    file = request.files['recipeimage']
    if file.filename == "":
        flash("Please select an image for the recipe!")
        return redirect(url_for("recipe.upload_recipe"))
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'],filename))
    else:
        flash("Could not upload image, please go back and try again")
        return redirect(url_for("recipe.upload_recipe"))
        
    url = file.filename
    create_new_recipe = UploadRecipe(
        r_title = data.get('recipetitle'), 
        r_cookingtime = data.get('recipetime'),
        r_image_url = url,
        r_serving = data.get('recipeserve'), 
        r_ingredient = data.get('recipeingredient'), 
        r_step = data.get('recipestep'), 
        r_about = data.get('recipeabout')
    )

    if create_new_recipe.save():   
        return redirect(url_for("recipe.show_customize_recipe"))
    else:
        return redirect(url_for("recipe.upload_recipe"))



@recipe_blueprint.route('/customize/<id>', methods=["GET"])
def show_recipe(id):
    c_recipe = UploadRecipe.get_or_none(UploadRecipe.id == id)
    return render_template("recipe/show_recipe.html", c_recipe = c_recipe)    



@recipe_blueprint.route('/customize/<id>/edit', methods=["GET"])
def edit_recipe(id):
    edit_recipe = UploadRecipe.get_or_none(UploadRecipe.id == id)
    return render_template("recipe/edit_recipe.html", edit_recipe = edit_recipe, id = id) 



@recipe_blueprint.route('/<id>/edit', methods=["POST"])
def update_recipe(id):
    update_recipe = UploadRecipe.get_or_none(UploadRecipe.id == id)
    data = request.form

    if update_recipe:
        if "recipeimage" not in request.files:
            flash("Please select an image for the recipe!")
            return redirect(url_for("recipe.edit_recipe",id = id))
        file = request.files['recipeimage']
        if file.filename == "":
            flash("Please select an image for the recipe!")
            return redirect(url_for("recipe.edit_recipe",id = id))
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'],filename))
        else:
            flash("Could not upload image, please go back and try again")
            return redirect(url_for("recipe.edit_recipe",id = id))
            
        url = file.filename

        update_recipe.r_title = data.get('recipetitle')
        update_recipe.r_cookingtime = data.get('recipetime')
        update_recipe.r_image_url = url
        update_recipe.r_serving = data.get('recipeserve')
        update_recipe.r_ingredient = data.get('recipeingredient')
        update_recipe.r_step = data.get('recipestep')
        update_recipe.r_about = data.get('recipeabout')
        
        

        if update_recipe.save():   
            return redirect(url_for("recipe.show_recipe", id=id))
        else:
            return redirect(url_for("recipe.edit_recipe", id=id))
    
    return render_template("recipe/edit_recipe.html", update_recipe = update_recipe, id = id)          


@recipe_blueprint.route('/meal_plan', methods=["GET"])
def meal_plan():
    return render_template("recipe/meal_plan.html")

@recipe_blueprint.route('/search_meal_plan', methods=['GET', 'POST'])
def search_meal_plan():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/mealplanner/generate?timeFrame=day&targetCalories=" + 
            (request.form['caloriesperday']) + "&diet=" +
            (request.form['diettype']) + "&exclude=" +
            (request.form['exclude_ingredient']) +
            "&number=20&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/meal_plan_result.html", response=json_response) if json_response != [] else render_template(
            "recipe/meal_plan_result.html", response="")
    else:
        return render_template("recipe/meal_plan.html") 


@recipe_blueprint.route('/search_meal_plan_weekly', methods=['GET', 'POST'])
def search_meal_plan_weekly():
    if request.method == 'POST':
        content = requests.get(
            "https://api.spoonacular.com/mealplanner/generate?timeFrame=week&targetCalories=" + 
            (request.form['caloriesperday']) + "&diet=" +
            (request.form['diettype']) + "&exclude=" +
            (request.form['exclude_ingredient']) +
            "&number=20&apiKey=" + app.config.get("SPOON_API"))
        json_response = json.loads(content.text)
        return render_template("recipe/meal_plan_weekly_result.html", response=json_response) if json_response != [] else render_template(
            "recipe/meal_plan_weekly_result.html", response="")
    else:
        return render_template("recipe/meal_plan.html")         

cookitnow_web/blueprints/recipe/templates/recipe/cooking_video.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header_video.html" %}
<div class="recipe-list">

  <div class="search-result">
    {% if response!=undefined and response|length > 0%}
    <h1>Video Found</h1>
    {% else %}
      {% if response!="No recipes found"%}
      <p>No recipes found</p>
      {% else %}
      {% endif %}
    {% endif %}

    
    <div class="search-result-list">
      <ul class="video_result">
        {% for search_result in response['videos'] %}
            <li>
                <div>
                    <div class="video-views"><i class="far fa-grin-hearts"></i> {{ search_result['views'] }}</div>
                    <iframe style="width:100%" height="315" src="https://www.youtube.com/embed/{{ search_result['youTubeId'] }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <div class="recipe_title">{{ search_result['title'] }}</div>
                </div>
            </li>
        {% endfor %}
      </ul>
    </div>
        
  </div>

</div>
{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/edit_recipe.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="flashes">
    <div class="close-flashes"><i class="fas fa-times"></i></div>
{% for message in messages %}
    <p>{{ message }}</p>
{% endfor %}
</div>
{% endif %}
{% endwith %}

<div class="upload-recipe">
    <h1>Edit Recipe {{edit_recipe.r_title}}</h1> 
 
    <div class="upload-form">
        <form method="POST" autocomplete="off" action="{{url_for('recipe.update_recipe', id = edit_recipe.id )}}" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class='input-group'>
                <label for="recipetitle">Recipe Title</label>
                <input type="text" name="recipetitle" class="input-field" value="{{edit_recipe.r_title}}">
            </div>

            <div class='input-group'>
                <label for="recipeimage">Recipe Feature Image</label>
                <input type="file" name="recipeimage" class="input-field" onchange="loadFile(event)" value="/static/images/uploaded_img/{{edit_recipe.r_image_url}}">
                <p class="notice">*accept only 'png', 'jpg', 'jpeg' type image, recommended with file name without space, example:"apple.png"</p>

                <p><img id="output" width="200" src="/static/images/uploaded_img/{{edit_recipe.r_image_url}}"/></p>
            </div>

            <script>
                var loadFile = function(event) {
                    var image = document.getElementById('output');
                    image.src = URL.createObjectURL(event.target.files[0]);
                };
            </script>

            <div class='input-group'>
                <label for="recipetime">Recipe Estimate Cooking Time</label>
                <input type="text" name="recipetime" class="input-field" value="{{edit_recipe.r_cookingtime}}">
            </div>

            <div class='input-group'>
                <label for="recipeserve">Recipe Serving Amount</label>
                <input type="text" name="recipeserve" class="input-field" value="{{edit_recipe.r_serving}}">
            </div>

            <div class='input-group'>
                <label for="recipeingredient">Recipe Ingredient</label>
                <textarea class="input-field" name="recipeingredient">{{edit_recipe.r_ingredient}}</textarea>
            </div>

            <div class='input-group'>
                <label for="recipestep">Recipe Step to Cook</label>
                <textarea class="input-field" name="recipestep">{{edit_recipe.r_step}}</textarea>
            </div>

            <div class='input-group'>
                <label for="recipeabout">Recipe About</label>
                <textarea class="input-field" name="recipeabout">{{edit_recipe.r_about}}</textarea>
            </div>

            <input type="submit" class="sub" value="Submit">
        </form>
    </div>

</div>
{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/meal_plan.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="flashes">
    <div class="close-flashes"><i class="fas fa-times"></i></div>
{% for message in messages %}
    <p>{{ message }}</p>
{% endfor %}
</div>
{% endif %}
{% endwith %}

<div class="mealplan">
    <h1>Check out our meal planning system!</h1>

    <div class="select-meal-plan">
        <div class="daily active">Daily Meal Plan</div>
        <div class="weekly">Weekly Meal Plan</div>
    </div>


    <div class="mealplan-form daily-mealplan">
        <form method="POST" autocomplete="off" action="{{url_for('recipe.search_meal_plan')}}" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class='input-group'>
                <label for="caloriesperday">Time Frame</label>
                <input type="text" value="DAY" class="input-field" readonly>
            </div>

            <div class='input-group'>
                <label for="caloriesperday">Target Calories per day</label>
                <input type="text" name="caloriesperday" placeholder="2000" class="input-field">
            </div>

            <div class='input-group'>
                <label>Diet Type</label>
                <select name="diettype" class="input-field">
                    <option value="vegetarian">Vegetarian</option>
                    <option value="ketogenic">Ketogenic</option>
                    <option value="lactovegetarian">Lacto-Vegetarian</option>
                    <option value="ovovegetarian">Ovo-Vegetarian</option>
                    <option value="vegan">Vegan</option>
                    <option value="paleo">Paleo</option>
                    <option value="primal">Primal</option>
                    <option value="whole30">Whole30</option>
                </select>
            </div>

            <div class='input-group'>
                <label for="exclude_ingredient">Exclude</label>
                <input type="text" name="exclude_ingredient" placeholder="shellfish, olives" class="input-field">
                <p class="notice">A comma-separated list of allergens or ingredients that must be excluded.</p>
            </div>

            <input type="submit" class="sub" value="Submit">
        </form>
    </div>

    <div class="mealplan-form weekly-mealplan" style="display:none"> 
        <form method="POST" autocomplete="off" action="{{url_for('recipe.search_meal_plan_weekly')}}" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class='input-group'>
                <label for="caloriesperday">Time Frame</label>
                <input type="text" value="WEEK" class="input-field" readonly>
            </div>

            <div class='input-group'>
                <label for="caloriesperday">Target Calories per day</label>
                <input type="text" name="caloriesperday" placeholder="2000" class="input-field">
            </div>

            <div class='input-group'>
                <label>Diet Type</label>
                <select name="diettype" class="input-field">
                    <option value="vegetarian">Vegetarian</option>
                    <option value="ketogenic">Ketogenic</option>
                    <option value="lactovegetarian">Lacto-Vegetarian</option>
                    <option value="ovovegetarian">Ovo-Vegetarian</option>
                    <option value="vegan">Vegan</option>
                    <option value="paleo">Paleo</option>
                    <option value="primal">Primal</option>
                    <option value="whole30">Whole30</option>
                </select>
            </div>

            <div class='input-group'>
                <label for="exclude_ingredient">Exclude</label>
                <input type="text" name="exclude_ingredient" placeholder="shellfish, olives" class="input-field">
                <p class="notice">A comma-separated list of allergens or ingredients that must be excluded.</p>
            </div>

            <input type="submit" class="sub" value="Submit">
        </form>
    </div>

</div>

<script>
$(".select-meal-plan > div").click(function(e) {
    $(this).addClass("active")
    $(this).siblings().removeClass("active")
});

$(".select-meal-plan .daily").click(function(e) {
    $(".weekly-mealplan").hide()
    $(".daily-mealplan").fadeIn()
});

$(".select-meal-plan .weekly").click(function(e) {
    $(".daily-mealplan").hide()
    $(".weekly-mealplan").fadeIn()
});
</script>
{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/meal_plan_result.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}
<div class="recipe-list">

  <div class="search-result">
    {% if response!=undefined and response|length > 0%}
    <h1>Daily Meal Plan</h1>
    {% else %}
      {% if response!="No recipes found"%}
      <p>No recipes found</p>
      {% else %}
      {% endif %}
    {% endif %}

    
    <div class="search-result-mealplan">
      <ul>
        {% for search_result in response["meals"] %}
        <li>
            <div class="image"><img id="recipeImage" src="https://spoonacular.com/recipeImages/{{search_result['id']}}-556x370.{{search_result['imageType']}}"></div>
            <div class="content">
                <div class="recipe_title">{{ search_result['title'] }}</div>
                <div class="recipe_time">Ready in <b>{{ search_result['readyInMinutes'] }}</b> minute</div>
                <div class="recipe_serve">Serve for <b>{{ search_result['servings'] }}</b> people</div>
                <a id="{{search_result['id']}}"  onclick="recipeDetails({{search_result['id']}})" class="images">Check Recipe</a>
            </div>      
        </li>
        {% endfor %}
      </ul>

      <div class="nutrients">
        <div>
            <div>
                <p>Calories: <b>{{ response["nutrients"]['calories'] }} kcal</b></p>
                <p>Carbohydrates: <b>{{ response["nutrients"]['carbohydrates'] }} gram</b></p>
                <p>Fat: <b>{{ response["nutrients"]['fat'] }} gram</b></p>       
                <p>Protein: <b>{{ response["nutrients"]['protein'] }} gram</b></p>
            </div>
        </div>
      </div>
    </div>
        
  </div>

</div>
{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/random_recipe.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}
<div class="recipe-list">

  <div class="search-result">
    {% if response!=undefined and response|length > 0%}
    <h1>Random 30 Recipe From CookItNow</h1>
    {% else %}
      {% if response!="No recipes found"%}
      <p>No recipes found</p>
      {% else %}
      {% endif %}
    {% endif %}

    
    <div class="search-result-list">
      <ul>
        {% for search_result in response['recipes'] %}
            <li>
              <div>
                <a id="{{search_result['id']}}"  onclick="recipeDetails({{search_result['id']}})" class="images">
                  <img id="recipeImage" src="{{search_result['image']}}">
                  <div class="recipe_likes_amount"><i class="far fa-thumbs-up"></i> {{ search_result['aggregateLikes'] }}</div>
                  <!-- <p>missed ingredient count : {{ search_result['missedIngredientCount'] }}</p>
                  <p>Favourited by others : {{ search_result['likes'] }}</p> -->
                </a>
    
                <div class="recipe_title"><a id="{{search_result['id']}}"  onclick="recipeDetails({{search_result['id']}})">{{ search_result['title'] }}</a></div>
              </div>
            </li>
        {% endfor %}
      </ul>
    </div>
        
  </div>

</div>
{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/recipe_details.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}
<div class="recipe_full_details">

    <div class="recipe_full_details_left">
        
        <div id="recipeTitle">
            {{ recipe_id['title'] }} <button id="downloadBtn" class='btn btn-link' onclick="getPdf()"><i class="fas fa-file-download"></i> Print Recipe</button>
        </div>

        <div class="recipe_food_images">
            <img id="recipeImage" src=" {{ recipe_id['image'] }}">
        </div>

        <div class="recipe_estimate_time">
            <div class="subtitle">Ready in</div>
            <p>Estimate <b>{{ recipe_id['readyInMinutes'] }}</b> min to cook</p>
        </div>

        <div class="recipe_serving">
            <div class="subtitle">Serve for</div>
            <p>{{ recipe_id['servings'] }} people</p>
        </div>

        <div class="recipe_ingredient_list">
            <div class="subtitle">Ingredients</div>
            <ul>
                {% for entry in recipe_id['extendedIngredients'] %}
                <li>{{entry['originalString']}}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="recipe_step_to_cook">
            <div class="subtitle">Steps to Follow</div>

            {% for step in recipe_id['analyzedInstructions'] %}
            <div class="step_name">{{ step['name']}}</div>
            <div class="step_details">
                <ul>
                {% for s in step['steps'] %}
                    <li>
                        <div class="step_count"><p>{{ s['number']}}</p></div>
                        <div class="step_desc">{{ s['step']}}<br></div>
                    </li>
                {% endfor %}
                </ul>
            </div>
            {% endfor %}

        </div>
    </div>

    <div class="recipe_full_details_right">

        <div class="recipe_about">
            <div class="subtitle">About This Recipe</div>
            <div id="recipeInstructions" class="recipeInstructions">{{ recipe_id['instructions'] | safe }}</div>
            <div class="recipe_original_from">Read the detail recipe on <a href="{{ recipe_id['sourceUrl'] }}">{{ recipe_id['sourceUrl'] }}</a></div>
        </div>

        <div class="recipe_equipment">
            <div class="subtitle">Equipment Needed</div>
            <div class="recipe_equipment_list">
                <ul>
                    {% for step in recipe_id['analyzedInstructions'] %}
                        {% for s in step['steps'] %}
                            {% for e in s['equipment'] %}
                                <li>
                                <p>{{ e['name']}}</p>
                                <img id="recipeImage" src="https://spoonacular.com/cdn/equipment_100x100/{{ e['image']}}">
                                </li>
                            {% endfor %}
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="recipe_all_ingredients">
            <div class="subtitle">Ingredients</div>
            <div class="recipe_ingredients_list">
                <ul>
                    {% for e in recipe_id['extendedIngredients'] %}
                    <li>
                        <p>{{e['name']}}</p>
                        <img src="https://spoonacular.com/cdn/ingredients_100x100/{{e['image']}}">
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>


    <div class="recipe_summary">
        <div class="subtitle">Summary of this Recipe</div>
        <div class="summary_desc">
            {{ recipe_id['summary'] | safe }}
        </div>
    </div>

    <div class="similar_recipe">
        <div class="subtitle">Similar Recipe</div>
        <div class="similar_recipe">
            <div class="search-result-list">
                <ul>
                    {% for s in recipe_similar %}
                    <li>
                    <div>
                        <a id="{{s['id']}}"  onclick="recipeDetails({{s['id']}})" class="images">
                        <img id="recipeImage" src="https://spoonacular.com/recipeImages/{{s['id']}}-556x370.{{s['imageType']}}">
                        </a>
                        <div class="recipe_title"><a id="{{s['id']}}"  onclick="recipeDetails({{s['id']}})">{{ s['title'] }}</a></div>
                    </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

</div>











{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/recipe_search.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}
<div class="recipe-list">

  <div class="search-result">
    {% if response!=undefined and response|length > 0%}
    <h1>Recipes Found</h1>
    {% else %}
      {% if response!="No recipes found"%}
      <p>No recipes found</p>
      {% else %}
      {% endif %}
    {% endif %}

    
    <div class="search-result-list">
      <ul>
        {% for search_result in response %}
        <li>
          <div>
            <div class="missing_ingredient">You need {{ search_result['missedIngredientCount'] }} more ingredient</div>
            <a id="{{search_result['id']}}"  onclick="recipeDetails({{search_result['id']}})" class="images">
              <img id="recipeImage" src="{{search_result['image']}}">
              <div class="recipe_likes_amount"><i class="far fa-thumbs-up"></i> {{ search_result['likes'] }}</div>
              <!-- <p>missed ingredient count : {{ search_result['missedIngredientCount'] }}</p>
              <p>Favourited by others : {{ search_result['likes'] }}</p> -->
            </a>

            <div class="recipe_title"><a id="{{search_result['id']}}"  onclick="recipeDetails({{search_result['id']}})">{{ search_result['title'] }}</a></div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
        
  </div>

</div>
{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/show_customize_recipe.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}
<div class="recipe-list">

  <div class="search-result">
    <h1>Our own customize recipe</h1>
    
    <div class="search-result-list customize-recipe">
      <ul>
        {% for show in all_recipe %}
        <li>
          <div>
            <a id="{{show.id}}"  href="{{url_for('recipe.show_recipe', id = show.id)}}" class="images">
                <img id="recipeImage" src="/static/images/uploaded_img/{{show.r_image_url}}">
              </a>
            <div class="recipe_title"><a id="{{show.id}}"  href="{{url_for('recipe.show_recipe', id = show.id)}}"> {{show.r_title}}</a></div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
        
  </div>

</div>
{% endblock %}

cookitnow_web/blueprints/recipe/templates/recipe/upload_recipe.html
{% extends "_layout.html" %}


{% block content %}
{% include "search_header.html" %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="flashes">
    <div class="close-flashes"><i class="fas fa-times"></i></div>
{% for message in messages %}
    <p>{{ message }}</p>
{% endfor %}
</div>
{% endif %}
{% endwith %}

<div class="upload-recipe">
    <h1>Upload New Recipe</h1> 
 
    <div class="upload-form">
        <form method="POST" autocomplete="off" action="{{url_for('recipe.create_recipe')}}" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class='input-group'>
                <label for="recipetitle">Recipe Title</label>
                <input type="text" name="recipetitle" class="input-field">
            </div>

            <div class='input-group'>
                <label for="recipeimage">Recipe Feature Image</label>
                <input type="file" name="recipeimage" class="input-field" onchange="loadFile(event)">
                <p class="notice">*accept only 'png', 'jpg', 'jpeg' type image, recommended with file name without space, example:"apple.png"</p>

                <p><img id="output" width="200" /></p>
            </div>

            <script>
                var loadFile = function(event) {
                    var image = document.getElementById('output');
                    image.src = URL.createObjectURL(event.target.files[0]);
                };
            </script>

            <div class='input-group'>
                <label for="recipetime">Recipe Estimate Cooking Time</label>
                <input type="text" name="recipetime" class="input-field">
            </div>

            <div class='input-group'>
                <label for="recipeserve">Recipe Serving Amount</label>
                <input type="text" name="recipeserve" class="input-field">
            </div>

            <div class='input-group'>
                <label for="recipeingredient">Recipe Ingredient</label>
                <textarea class="input-field" name="recipeingredient"></textarea>
            </div>

            <div class='input-group'>
                <label for="recipestep">Recipe Step to Cook</label>
                <textarea class="input-field" name="recipestep"></textarea>
            </div>

            <div class='input-group'>
                <label for="recipeabout">Recipe About</label>
                <textarea class="input-field" name="recipeabout"></textarea>
            </div>

            <input type="submit" class="sub" value="Submit">
        </form>
    </div>

</div>
{% endblock %}